# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384a3e0d7add58f65c0522edbc005d5a4ed49fb68851d5d3c860439c67c8fad5f271f2a0abb445a2c1de456b07f8917f5af6710200ebf1f1808dca0e476f9e6e

test:
  secret_key_base: 67fed7c77134193791d21d8094808d017759bb0c7d947b9b91fc59866d362ba011425bb104b6c81b1e4e7d23c655319b6022b9405380b86cbf235da45fb17121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
